import { Inter } from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <header className="bg-gray-800 text-white py-4">
            <div className="container mx-auto flex justify-between items-center px-6">
              <div className="text-lg font-semibold">
                <a href="/" className="hover:text-gray-200">
                  MSC
                </a>
              </div>
              <nav>
                <SignedOut>
                  <SignInButton className="text-sm bg-blue-500 hover:bg-blue-700 px-4 py-2 rounded shadow" />
                </SignedOut>
                <SignedIn>
                  <UserButton className="text-sm bg-green-500 hover:bg-green-700 px-4 py-2 rounded shadow" />
                </SignedIn>
              </nav>
            </div>
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
